/* NVIDIA proprietary GPU driver ioctl definitions.
 *
 * Sourced from NVIDIA's open-gpu-kernel-modules repository
 * (kernel-open/common/inc/nv-ioctl-numbers.h, nv-ioctl.h),
 * which is licensed under the MIT license.
 *
 * These are not part of the upstream Linux kernel headers, so they are
 * maintained here manually rather than generated by maint/ioctls_gen.sh.
 */
{ "nvidia/nv-ioctl.h", "NV_ESC_CARD_INFO", _IOC_READ, 0x46c8, 0x48 },
{ "nvidia/nv-ioctl.h", "NV_ESC_REGISTER_FD", _IOC_WRITE, 0x46c9, 0x04 },
{ "nvidia/nv-ioctl.h", "NV_ESC_ALLOC_OS_EVENT", _IOC_READ|_IOC_WRITE, 0x46ce, 0x10 },
{ "nvidia/nv-ioctl.h", "NV_ESC_FREE_OS_EVENT", _IOC_READ|_IOC_WRITE, 0x46cf, 0x10 },
{ "nvidia/nv-ioctl.h", "NV_ESC_STATUS_CODE", _IOC_READ|_IOC_WRITE, 0x46d1, 0x0c },
{ "nvidia/nv-ioctl.h", "NV_ESC_CHECK_VERSION_STR", _IOC_READ|_IOC_WRITE, 0x46d2, 0x48 },
{ "nvidia/nv-ioctl.h", "NV_ESC_IOCTL_XFER_CMD", _IOC_READ|_IOC_WRITE, 0x46d3, 0x10 },
{ "nvidia/nv-ioctl.h", "NV_ESC_ATTACH_GPUS_TO_FD", _IOC_WRITE, 0x46d4, 0x04 },
{ "nvidia/nv-ioctl.h", "NV_ESC_QUERY_DEVICE_INTR", _IOC_READ|_IOC_WRITE, 0x46d5, 0x08 },
{ "nvidia/nv-ioctl.h", "NV_ESC_SYS_PARAMS", _IOC_READ|_IOC_WRITE, 0x46d6, 0x08 },
{ "nvidia/nv-ioctl.h", "NV_ESC_EXPORT_TO_DMABUF_FD", _IOC_READ|_IOC_WRITE, 0x46d9, 0xa2c },
{ "nvidia/nv-ioctl.h", "NV_ESC_WAIT_OPEN_COMPLETE", _IOC_READ|_IOC_WRITE, 0x46da, 0x08 },
